In [1]:
import numpy as np

In [2]:
list1 = [1, 2, 3]

array1 = np.array(list1)

In [3]:
array1.shape

(3,)

In [4]:
array2 = np.array([[1,2,3],[4,5,6]])
array2.shape

(2, 3)

In [5]:
array3 = np.array([[1,2,]])
array3.shape

(1, 2)

In [6]:
array1.dtype

dtype('int32')

In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
array2.dtype

dtype('<U11')

In [10]:
list3 = [1, 2, 3.0]
array3 = np.array(list3)
array3.dtype

dtype('float64')

In [12]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float')
array_float.dtype

dtype('float64')

In [13]:
array = np.array([[1,2,3],[4,5,6]])
print(array.sum())
print(array.sum(axis=0))
print(array.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.zeros((3,2), dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
array1 = np.arange(10)
array1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
array1 = np.arange(10)
array1.reshape(-1,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
array1 = np.arange(10)
array1.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [23]:
array1 = np.arange(10)
array1.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
array1 = np.arange(10)
array1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
array1.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
array1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
array1d =  np.arange(1,10)

In [49]:
array2d = array1.reshape(3,3)

In [51]:
array2d[[0,1],2]

array([3, 6])

In [52]:
array2d[[0,2], 0:2]

array([[1, 2],
       [7, 8]])

In [53]:
array2d[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
array1d[array1d>5]

array([6, 7, 8, 9])

In [55]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [56]:
array2d>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [63]:
indexes = np.array([5,6,7,8])
array2 = array1d[indexes]

In [82]:
array2d.sort()

In [86]:
array2d.sort(axis=0)

In [96]:
np.sort([[5,1,8],[2,9,4],[6,7,3]],axis=0)

array([[2, 1, 3],
       [5, 7, 4],
       [6, 9, 8]])

In [91]:
array2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [92]:
array2d.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [100]:
name_array = np.array(['John', 'Mike', 'Sarah','Kate', 'Samuel'])
score_array = np.array([78, 95,84, 98, 88])

sort_indices = np.argsort(score_array)
print('sort_indices', sort_indices)

name_array_sort = name_array[sort_indices]

score_array_sort = score_array[sort_indices]

print(name_array_sort)
print(score_array_sort)

sort_indices [0 2 4 1 3]
['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


In [103]:
array = np.array([1,3,4,2,5])
array[[0,3,1,2,4]]

array([1, 2, 3, 4, 5])

In [104]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


In [105]:
A = np.array([[1,2],[3,4]])
A.transpose()

array([[1, 3],
       [2, 4]])